// lib/mock-data.ts
import { Company } from "@/types";

export const MOCK_COMPANIES: Company[] = [
  {
    id: "1",
    name: "Nebula AI",
    url: "https://openai.com",
    description: "Generative AI infrastructure for enterprise workflows.",
    industry: "Artificial Intelligence",
    location: "San Francisco, CA",
    foundedYear: 2023,
    stage: "Series A",
    isEnriched: false,
  },
  {
    id: "2",
    name: "EcoFlow Dynamics",
    url: "https://climatescape.org",
    description: "Carbon capture and storage solutions for heavy industry.",
    industry: "Climate Tech",
    location: "Austin, TX",
    foundedYear: 2022,
    stage: "Seed",
    isEnriched: false,
  },
  {
    id: "3",
    name: "Quantal Health",
    url: "https://deepmind.google",
    description: "Quantum computing applications for drug discovery.",
    industry: "BioTech",
    location: "Boston, MA",
    foundedYear: 2024,
    stage: "Seed",
    isEnriched: false,
  },
  {
    id: "4",
    name: "CyberShield Ops",
    url: "https://crowdstrike.com",
    description: "Autonomous threat detection for cloud infrastructure.",
    industry: "Cybersecurity",
    location: "Tel Aviv, Israel",
    foundedYear: 2021,
    stage: "Series B",
    isEnriched: false,
  },
  {
    id: "5",
    name: "Orbital Logistics",
    url: "https://spacex.com",
    description: "Last-mile delivery networks for low-earth orbit satellites.",
    industry: "Space Tech",
    location: "Los Angeles, CA",
    foundedYear: 2020,
    stage: "Growth",
    isEnriched: false,
  },

  // --- Additional Companies ---

  {
    id: "6",
    name: "FinNova Labs",
    url: "https://stripe.com",
    description: "Embedded fintech APIs for cross-border payments.",
    industry: "FinTech",
    location: "London, UK",
    foundedYear: 2022,
    stage: "Series A",
    isEnriched: false,
  },
  {
    id: "7",
    name: "AgriPulse Systems",
    url: "https://climate.com",
    description: "AI-powered precision agriculture analytics.",
    industry: "AgriTech",
    location: "Des Moines, IA",
    foundedYear: 2021,
    stage: "Seed",
    isEnriched: false,
  },
  {
    id: "8",
    name: "MedSynapse",
    url: "https://mayo.edu",
    description: "Predictive diagnostics using multimodal health data.",
    industry: "HealthTech",
    location: "Rochester, MN",
    foundedYear: 2023,
    stage: "Pre-Seed",
    isEnriched: false,
  },
  {
    id: "9",
    name: "VoltEdge Mobility",
    url: "https://tesla.com",
    description: "Battery optimization software for EV fleets.",
    industry: "Clean Energy",
    location: "Berlin, Germany",
    foundedYear: 2022,
    stage: "Series A",
    isEnriched: false,
  },
  {
    id: "10",
    name: "DataForge Analytics",
    url: "https://snowflake.com",
    description: "Real-time enterprise data orchestration platform.",
    industry: "Data Infrastructure",
    location: "New York, NY",
    foundedYear: 2020,
    stage: "Series B",
    isEnriched: false,
  },
  {
    id: "11",
    name: "BlockWave Systems",
    url: "https://ethereum.org",
    description: "Decentralized identity and compliance protocols.",
    industry: "Web3",
    location: "Singapore",
    foundedYear: 2023,
    stage: "Seed",
    isEnriched: false,
  },
  {
    id: "12",
    name: "NeuroGrid Labs",
    url: "https://nvidia.com",
    description: "Edge AI hardware acceleration for robotics.",
    industry: "Artificial Intelligence",
    location: "San Jose, CA",
    foundedYear: 2021,
    stage: "Series A",
    isEnriched: false,
  },
  {
    id: "13",
    name: "SkyFarm Robotics",
    url: "https://bostondynamics.com",
    description: "Autonomous greenhouse management systems.",
    industry: "Robotics",
    location: "Rotterdam, Netherlands",
    foundedYear: 2022,
    stage: "Seed",
    isEnriched: false,
  },
  {
    id: "14",
    name: "AquaChain Solutions",
    url: "https://worldbank.org",
    description: "Blockchain-enabled water resource tracking.",
    industry: "Climate Tech",
    location: "Cape Town, South Africa",
    foundedYear: 2023,
    stage: "Pre-Seed",
    isEnriched: false,
  },
  {
    id: "15",
    name: "SecureLayer AI",
    url: "https://paloaltonetworks.com",
    description: "AI-native zero-trust security architecture.",
    industry: "Cybersecurity",
    location: "Bangalore, India",
    foundedYear: 2022,
    stage: "Series A",
    isEnriched: false,
  },
  {
    id: "16",
    name: "BioForge Therapeutics",
    url: "https://genentech.com",
    description: "Synthetic biology for targeted cancer therapies.",
    industry: "BioTech",
    location: "San Diego, CA",
    foundedYear: 2020,
    stage: "Series B",
    isEnriched: false,
  },
  {
    id: "17",
    name: "HyperRoute Logistics",
    url: "https://ups.com",
    description: "AI-driven route optimization for logistics fleets.",
    industry: "Logistics Tech",
    location: "Chicago, IL",
    foundedYear: 2021,
    stage: "Series A",
    isEnriched: false,
  },
  {
    id: "18",
    name: "MetaLearn Systems",
    url: "https://coursera.org",
    description: "Adaptive learning platforms powered by GenAI.",
    industry: "EdTech",
    location: "Toronto, Canada",
    foundedYear: 2023,
    stage: "Seed",
    isEnriched: false,
  },
  {
    id: "19",
    name: "FusionCore Energy",
    url: "https://iter.org",
    description: "Commercial small-scale fusion reactor systems.",
    industry: "Energy",
    location: "Paris, France",
    foundedYear: 2024,
    stage: "Pre-Seed",
    isEnriched: false,
  },
  {
    id: "20",
    name: "RetailMind AI",
    url: "https://shopify.com",
    description: "Predictive demand forecasting for e-commerce brands.",
    industry: "Retail Tech",
    location: "Vancouver, Canada",
    foundedYear: 2021,
    stage: "Series A",
    isEnriched: false,
  },
  {
    id: "21",
    name: "DeepVision Systems",
    url: "https://meta.com",
    description: "Computer vision solutions for AR applications.",
    industry: "Augmented Reality",
    location: "Seattle, WA",
    foundedYear: 2022,
    stage: "Seed",
    isEnriched: false,
  },
  {
    id: "22",
    name: "OceanGrid Analytics",
    url: "https://noaa.gov",
    description: "Satellite-driven ocean climate modeling.",
    industry: "Climate Tech",
    location: "Sydney, Australia",
    foundedYear: 2023,
    stage: "Pre-Seed",
    isEnriched: false,
  },
  {
    id: "23",
    name: "QuantumSecure Labs",
    url: "https://ibm.com",
    description: "Post-quantum cryptography solutions.",
    industry: "Cybersecurity",
    location: "Zurich, Switzerland",
    foundedYear: 2022,
    stage: "Series A",
    isEnriched: false,
  },
  {
    id: "24",
    name: "FleetSense AI",
    url: "https://uber.com",
    description: "Telematics intelligence for ride-sharing fleets.",
    industry: "Mobility Tech",
    location: "Dubai, UAE",
    foundedYear: 2021,
    stage: "Series A",
    isEnriched: false,
  },
  {
    id: "25",
    name: "SolarWeave Technologies",
    url: "https://firstsolar.com",
    description: "Smart solar fabric for urban infrastructure.",
    industry: "Clean Energy",
    location: "Barcelona, Spain",
    foundedYear: 2023,
    stage: "Seed",
    isEnriched: false,
  },
  {
    id: "26",
    name: "ChainLedger Systems",
    url: "https://polygon.technology",
    description: "Enterprise-grade blockchain audit tooling.",
    industry: "Web3",
    location: "Mumbai, India",
    foundedYear: 2022,
    stage: "Series A",
    isEnriched: false,
  },
  {
    id: "27",
    name: "HelixAI Robotics",
    url: "https://abb.com",
    description: "Collaborative robotics for smart factories.",
    industry: "Industrial Tech",
    location: "Stockholm, Sweden",
    foundedYear: 2021,
    stage: "Series B",
    isEnriched: false,
  },
  {
    id: "28",
    name: "NeuraLink Analytics",
    url: "https://oracle.com",
    description: "Cognitive enterprise decision-support systems.",
    industry: "Enterprise AI",
    location: "Dallas, TX",
    foundedYear: 2020,
    stage: "Growth",
    isEnriched: false,
  },
  {
    id: "29",
    name: "TerraQuant Systems",
    url: "https://esri.com",
    description: "Geospatial AI for urban planning.",
    industry: "GeoTech",
    location: "Denver, CO",
    foundedYear: 2022,
    stage: "Seed",
    isEnriched: false,
  },
  {
    id: "30",
    name: "PulseChain Health",
    url: "https://who.int",
    description: "Blockchain-backed patient data interoperability.",
    industry: "HealthTech",
    location: "Geneva, Switzerland",
    foundedYear: 2023,
    stage: "Pre-Seed",
    isEnriched: false,
  },
];
